# Generated by Django 5.0.1 on 2024-02-20 14:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Beperkingen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auditieve_beperkingen', models.CharField(blank=True, choices=[('doof', 'Doof'), ('slechthorend', 'Slechthorend'), ('doofblind', 'Doofblind')], max_length=50, null=True)),
                ('visuele_beperkingen', models.CharField(blank=True, choices=[('blind', 'Blind'), ('slechtziend', 'Slechtziend'), ('kleurenblind', 'Kleurenblind'), ('doofblind', 'Doofblind')], max_length=50, null=True)),
                ('motorische_lichamelijke_beperkingen', models.CharField(blank=True, choices=[('amputatie', 'Amputatie en mismaaktheid'), ('artritus', 'Artritus'), ('fibromyalgie', 'Fibromyalgie'), ('reuma', 'Reuma'), ('handvaardigheid', 'Verminderde handvaardigheid'), ('spierdystrofie', 'Spierdystrofie'), ('rsi', 'RSI'), ('tremor', 'Tremor en Spasmen'), ('quadriplegie', 'Quadriplegie of tetraplegie')], max_length=50, null=True)),
                ('cognitieve_neurologische_beperkingen', models.CharField(blank=True, choices=[('adhd', 'ADHD'), ('autisme', 'Autisme'), ('leerstoornis', 'Leerstoornis'), ('geheugen', 'Geheugen beperking'), ('ms', 'Multiple Sclerose'), ('epilepsie', 'Epilepsie'), ('migraine', 'Migraine')], max_length=50, null=True)),
            ],
            options={
                'db_table': 'beperkingen',
            },
        ),
        migrations.CreateModel(
            name='Hulpmiddelen',
            fields=[
                ('hulpmiddelen_id', models.AutoField(primary_key=True, serialize=False)),
                ('vergrootglas', models.BooleanField(default=False)),
                ('scherm_voorlezer', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'hulpmiddelen',
            },
        ),
        migrations.CreateModel(
            name='Inschrijvingen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naam', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('inschrijvingsdatum', models.DateField(auto_now_add=True)),
                ('is_goedgekeurd', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Organisaties',
            fields=[
                ('organisatie_id', models.AutoField(primary_key=True, serialize=False)),
                ('naam', models.CharField(max_length=255)),
                ('type', models.CharField(blank=True, max_length=255, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('beschrijving', models.TextField(blank=True, null=True)),
                ('contactpersoon', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('telefoonnummer', models.CharField(blank=True, max_length=20, null=True)),
                ('overige_details', models.TextField(blank=True, null=True)),
                ('api_key', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'organisaties',
            },
        ),
        migrations.CreateModel(
            name='Toezichthouder',
            fields=[
                ('toezichthouder_id', models.AutoField(primary_key=True, serialize=False)),
                ('naam', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('telefoonnummer', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'toezichthouder',
            },
        ),
        migrations.CreateModel(
            name='Gebruikers',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('gebruiker_id', models.AutoField(primary_key=True, serialize=False)),
                ('voornaam', models.CharField(max_length=255)),
                ('achternaam', models.CharField(max_length=255)),
                ('is_beheerder', models.BooleanField(default=False)),
                ('postcode', models.CharField(blank=True, max_length=6, null=True)),
                ('geslacht', models.CharField(blank=True, max_length=10, null=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telefoonnummer', models.CharField(blank=True, max_length=20, null=True)),
                ('geboortedatum', models.DateField()),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'gebruikers',
            },
        ),
        migrations.CreateModel(
            name='Ervaringsdeskundige',
            fields=[
                ('ervaringsdeskundige_id', models.AutoField(primary_key=True, serialize=False)),
                ('bijzonderheden', models.TextField(blank=True, null=True)),
                ('voorkeur_benadering', models.CharField(blank=True, max_length=255, null=True)),
                ('bijzonderheden_beschikbaar', models.CharField(blank=True, max_length=255, null=True)),
                ('is_goedgekeurd', models.BooleanField(default=False)),
                ('beperkingen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.beperkingen')),
                ('gebruiker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('hulpmiddelen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.hulpmiddelen')),
                ('toezichthouder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.toezichthouder')),
            ],
            options={
                'db_table': 'ervaringsdeskundige',
            },
        ),
        migrations.CreateModel(
            name='Onderzoek',
            fields=[
                ('onderzoek_id', models.AutoField(primary_key=True, serialize=False)),
                ('titel', models.CharField(max_length=255)),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
                ('beschikbaar', models.BooleanField(default=True)),
                ('datum_vanaf', models.DateField(blank=True, null=True)),
                ('datum_tot', models.DateField(blank=True, null=True)),
                ('type_onderzoek', models.CharField(blank=True, max_length=50, null=True)),
                ('locatie', models.CharField(blank=True, max_length=255, null=True)),
                ('met_beloning', models.BooleanField(default=False)),
                ('beloning', models.CharField(blank=True, max_length=255, null=True)),
                ('doelgroep_leeftijd_van', models.IntegerField(blank=True, null=True)),
                ('doelgroep_leeftijd_tot', models.IntegerField(blank=True, null=True)),
                ('doelgroep_beperking', models.CharField(blank=True, max_length=255, null=True)),
                ('organisatie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.organisaties')),
            ],
            options={
                'db_table': 'Onderzoek',
            },
        ),
        migrations.CreateModel(
            name='OnderzoekErvaringsdeskundige',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_goedgekeurd', models.BooleanField(default=False)),
                ('ervaringsdeskundige', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.ervaringsdeskundige')),
                ('onderzoek', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.onderzoek')),
            ],
            options={
                'db_table': 'onderzoek_ervaringsdeskundige',
                'unique_together': {('onderzoek', 'ervaringsdeskundige')},
            },
        ),
    ]
