# Generated by Django 5.0.1 on 2024-02-15 15:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Beperkingen',
            fields=[
                ('beperkingen_id', models.AutoField(primary_key=True, serialize=False)),
                ('auditieve_beperkingen', models.CharField(blank=True, max_length=255, null=True)),
                ('visuele_beperkingen', models.CharField(blank=True, max_length=255, null=True)),
                ('motorische_lichamelijke_beperkingen', models.CharField(blank=True, max_length=255, null=True)),
                ('cognitieve_neurologische_beperkingen', models.CharField(blank=True, max_length=255, null=True)),
                ('reden_beperking', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'beperkingen',
            },
        ),
        migrations.CreateModel(
            name='Gebruikers',
            fields=[
                ('gebruiker_id', models.AutoField(primary_key=True, serialize=False)),
                ('voornaam', models.CharField(max_length=255)),
                ('achternaam', models.CharField(max_length=255)),
                ('is_beheerder', models.BooleanField(default=False)),
                ('postcode', models.CharField(blank=True, max_length=6, null=True)),
                ('geslacht', models.CharField(blank=True, max_length=10, null=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('wachtwoord', models.CharField(max_length=255)),
                ('telefoonnummer', models.CharField(blank=True, max_length=20, null=True)),
                ('geboortedatum', models.DateField()),
            ],
            options={
                'db_table': 'gebruikers',
            },
        ),
        migrations.CreateModel(
            name='Hulpmiddelen',
            fields=[
                ('hulpmiddelen_id', models.AutoField(primary_key=True, serialize=False)),
                ('vergrootglas', models.BooleanField(default=False)),
                ('scherm_voorlezer', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'hulpmiddelen',
            },
        ),
        migrations.CreateModel(
            name='Organisaties',
            fields=[
                ('organisatie_id', models.AutoField(primary_key=True, serialize=False)),
                ('naam', models.CharField(max_length=255)),
                ('type', models.CharField(blank=True, max_length=255, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('beschrijving', models.TextField(blank=True, null=True)),
                ('contactpersoon', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('telefoonnummer', models.CharField(blank=True, max_length=20, null=True)),
                ('overige_details', models.TextField(blank=True, null=True)),
                ('api_key', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'organisaties',
            },
        ),
        migrations.CreateModel(
            name='Toezichthouder',
            fields=[
                ('toezichthouder_id', models.AutoField(primary_key=True, serialize=False)),
                ('naam', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('telefoonnummer', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'toezichthouder',
            },
        ),
        migrations.CreateModel(
            name='Ervaringsdeskundige',
            fields=[
                ('ervaringsdeskundige_id', models.AutoField(primary_key=True, serialize=False)),
                ('bijzonderheden', models.TextField(blank=True, null=True)),
                ('voorkeur_benadering', models.CharField(blank=True, max_length=255, null=True)),
                ('bijzonderheden_beschikbaar', models.CharField(blank=True, max_length=255, null=True)),
                ('beperkingen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.beperkingen')),
                ('gebruiker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.gebruikers')),
                ('hulpmiddelen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.hulpmiddelen')),
                ('toezichthouder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.toezichthouder')),
            ],
            options={
                'db_table': 'ervaringsdeskundige',
            },
        ),
        migrations.CreateModel(
            name='Onderzoek',
            fields=[
                ('onderzoek_id', models.AutoField(primary_key=True, serialize=False)),
                ('titel', models.CharField(max_length=255)),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
                ('beschikbaar', models.BooleanField(default=True)),
                ('datum_vanaf', models.DateField(blank=True, null=True)),
                ('datum_tot', models.DateField(blank=True, null=True)),
                ('type_onderzoek', models.CharField(blank=True, max_length=50, null=True)),
                ('locatie', models.CharField(blank=True, max_length=255, null=True)),
                ('met_beloning', models.BooleanField(default=False)),
                ('beloning', models.CharField(blank=True, max_length=255, null=True)),
                ('doelgroep_leeftijd_van', models.IntegerField(blank=True, null=True)),
                ('doelgroep_leeftijd_tot', models.IntegerField(blank=True, null=True)),
                ('doelgroep_beperking', models.CharField(blank=True, max_length=255, null=True)),
                ('organisatie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.organisaties')),
            ],
            options={
                'db_table': 'Onderzoek',
            },
        ),
        migrations.CreateModel(
            name='OnderzoekErvaringsdeskundige',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ervaringsdeskundige', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.ervaringsdeskundige')),
                ('onderzoek', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.onderzoek')),
            ],
            options={
                'db_table': 'onderzoek_ervaringsdeskundige',
                'unique_together': {('onderzoek', 'ervaringsdeskundige')},
            },
        ),
    ]
