# Generated by Django 5.0.1 on 2024-02-26 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="gebruikers",
            name="is_organisatie",
            field=models.BooleanField(default=False),
        ),
    ]
