# Generated by Django 5.0.1 on 2024-02-15 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gebruikers',
            name='email',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
