# Generated by Django 5.0.1 on 2024-03-01 12:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_gebruikers_is_organisatie"),
    ]

    operations = [
        migrations.AddField(
            model_name="gebruikers",
            name="organisatie",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.organisaties",
            ),
        ),
    ]
