# Generated by Django 5.0.1 on 2024-02-19 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_gebruikers_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inschrijvingen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naam', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('inschrijvingsdatum', models.DateField(auto_now_add=True)),
                ('is_goedgekeurd', models.BooleanField(default=False)),
            ],
        ),
    ]
