# Generated by Django 5.0.1 on 2024-02-19 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_inschrijvingen'),
    ]

    operations = [
        migrations.AddField(
            model_name='ervaringsdeskundige',
            name='is_goedgekeurd',
            field=models.BooleanField(default=False),
        ),
    ]
