# Generated by Django 5.0.1 on 2024-03-07 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_onderzoek_omschrijving'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Inschrijvingen',
        ),
    ]
