# Generated by Django 5.0.1 on 2024-02-19 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_ervaringsdeskundige_is_goedgekeurd"),
    ]

    operations = [
        migrations.AddField(
            model_name="gebruikers",
            name="last_login",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
