# Generated by Django 5.0.1 on 2024-03-13 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_delete_inschrijvingen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onderzoekervaringsdeskundige',
            name='is_goedgekeurd',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
