# Generated by Django 5.0.1 on 2024-02-19 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_gebruikers_last_login"),
    ]

    operations = [
        migrations.AddField(
            model_name="gebruikers",
            name="is_authenticated",
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
