# Generated by Django 5.0.1 on 2024-03-19 13:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_onderzoekervaringsdeskundige_is_goedgekeurd'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notificatie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bericht', models.CharField(max_length=255)),
                ('is_gelezen', models.BooleanField(default=False)),
                ('aangemaakt_op', models.DateTimeField(auto_now_add=True)),
                ('ontvanger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaties', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notificaties',
                'ordering': ['-aangemaakt_op'],
            },
        ),
    ]
