# Generated by Django 5.0.1 on 2024-02-19 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_onderzoekervaringsdeskundige_is_goedgekeurd"),
        ("core", "0006_gebruikers_is_authenticated"),
    ]

    operations = []
