# Generated by Django 5.0.1 on 2024-03-19 14:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_notificatie'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificatie',
            name='onderzoek',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.onderzoek'),
        ),
    ]
