# Generated by Django 5.0.1 on 2024-03-19 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_notificatie_onderzoek'),
    ]

    operations = [
        migrations.AddField(
            model_name='onderzoekervaringsdeskundige',
            name='notificatie_verzonden',
            field=models.BooleanField(default=False),
        ),
    ]
